
server:
 port: 8770
 #MQTT配置信息
spring:
 mqtt:
  #MQTT-用户名
  username: admin1
   #MQTT-密码
  password: admin1
   #MQTT-服务器连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613，tcp://192.168.2.133:61613
  url: tcp://127.0.0.1:1883
   #MQTT-连接服务器默认客户端ID
  client:
   id: mqttId111
   #MQTT-默认的消息推送主题，实际可在调用接口时指定(生产者 发送)
  default:
   topic: topic
   # 连接服务器默认客户端ID
  consumer:
   clientId: mqttId222
   defaultTopic: hello,topics1
   # 默认的接收主题，可以订阅(消费者 接收)多个Topic，逗号分隔
